import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {ThemeProvider} from "@/components/theme/theme-provider";
import {ThemeToggle} from "@/components/theme/theme-toggle";
import {AppReadyProvider} from "@/components/providers/app-ready-provider";
import {getUnleashSessionId} from "@/lib/unleash-session";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "C-Cloud",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const sessionId = await getUnleashSessionId();
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <AppReadyProvider sessionId={sessionId}>
                {children}
            </AppReadyProvider>
            <div className="fixed bottom-4 right-4 z-50">
                <ThemeToggle/>
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
