spring:
  cloud:
    stream:
      bindings:
        authEmailNotification-out-0:
          destination: auth-email-notifications
          content-type: application/json
      rabbit:
        bindings:
          authEmailNotification-out-0:
            producer:
              exchange-type: direct
              routing-key-expression: '"auth.email.notification"'


app:
  messaging:
    email-notification-binding: authEmailNotification-out-0